language: perl

install:
  - cpanm -n Mojolicious
  - cpanm -n File::HomeDir
  - cpanm -n File::HomeDir::Test

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"

script: HARNESS_IS_VERBOSE=1 prove -lv t xt
